grpc_server:
  socket_path: /etc/kubeedge/modbus.sock
common:
  name: modbus-dmi-mapper
  version: v1.13.0
  api_version: v1.0.0
  protocol: modbus
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
dev_init:
  mode: register #register/configmap
